{{- if .Values.secretManager.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-k8s-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Release.Name }}-aws-secretsmanager
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-k8s-secret
    creationPolicy: Owner
  data:
    - secretKey: APP_NAME
      remoteRef:
        key: {{ .Values.secretManager.secretName }}
        property: APP_NAME
    - secretKey: APP_ENV
      remoteRef:
        key: {{ .Values.secretManager.secretName }}
        property: APP_ENV
    - secretKey: APP_DEBUG
      remoteRef:
        key: {{ .Values.secretManager.secretName }}
        property: APP_DEBUG
    - secretKey: APP_URL
      remoteRef:
        key: {{ .Values.secretManager.secretName }}
        property: APP_URL
    - secretKey: SOCKET_PORT
      remoteRef:
        key: {{ .Values.secretManager.secretName }}
        property: SOCKET_PORT
    - secretKey: LOG_CHANNEL
      remoteRef:
        key: {{ .Values.secretManager.secretName }}
        property: LOG_CHANNEL
    - secretKey: LOG_LEVEL
      remoteRef:
        key: {{ .Values.secretManager.secretName }}
        property: LOG_LEVEL
    - secretKey: DB_CONNECTION
      remoteRef:
        key: {{ .Values.secretManager.secretName }}
        property: DB_CONNECTION
    - secretKey: DB_HOST
      remoteRef:
        key: {{ .Values.secretManager.secretName }}
        property: DB_HOST
    - secretKey: DB_PORT
      remoteRef:
        key: {{ .Values.secretManager.secretName }}
        property: DB_PORT
    - secretKey: DB_DATABASE
      remoteRef:
        key: {{ .Values.secretManager.secretName }}
        property: DB_DATABASE
    - secretKey: DB_USERNAME
      remoteRef:
        key: {{ .Values.secretManager.secretName }}
        property: DB_USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.secretManager.secretName }}
        property: DB_PASSWORD
    - secretKey: CALLBACK_HOST
      remoteRef:
        key: {{ .Values.secretManager.secretName }}
        property: CALLBACK_HOST
    - secretKey: JWT_SECRET
      remoteRef:
        key: {{ .Values.secretManager.secretName }}
        property: JWT_SECRET
    - secretKey: API_PASSWORD
      remoteRef:
        key: {{ .Values.secretManager.secretName }}
        property: API_PASSWORD
    - secretKey: API_PASSWORD_WITHDRAW
      remoteRef:
        key: {{ .Values.secretManager.secretName }}
        property: API_PASSWORD_WITHDRAW
    - secretKey: API_PASSWORD_WITHDRAW_User_12
      remoteRef:
        key: {{ .Values.secretManager.secretName }}
        property: API_PASSWORD_WITHDRAW_User_12
{{- end }}
