{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

    # SSL Redirect ayarı
    {{- if .Values.ingress.sslRedirect }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- else }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{- end }}

    # Backend protokol ayarı (HTTP)
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

spec:
  ingressClassName: "nginx"  # NGINX Ingress Controller sınıfı
  rules:
    - host: {{ .Values.ingress.host }}  # Domain adınız
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-service
                port:
                  number: 80  # Uygulamanızın dinlediği port
{{- end }}
