{{- if .Values.secretManager.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Release.Name }}-aws-secretsmanager
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.secretManager.serviceAccountName }}
            namespace: {{ .Release.Namespace }}
{{- end }}
