{{- if .Values.secretManager.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.secretManager.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.secretManager.roleArn }}
{{- end }}
